apiVersion: azconfig.io/v1
kind: AzureAppConfigurationProvider
metadata:
  name:  messaging-hub-api-appconfig-provider
spec:
  endpoint: ${APP_CONFIG_ENDPOINT}
  target:
    configMapName: messaging-hub-api-appconfig
    configMapData: 
      type: json
      key: config.json
  configuration:
    selectors:
      - keyFilter: "*"
        labelFilter: messaging-hub-api
  auth:
    workloadIdentity:
      serviceAccountName: messaging-hub-api-sa