apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-hub-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging-hub-api
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
        app: messaging-hub-api
    spec:
      serviceAccountName: messaging-hub-api-sa
      containers:
        - name: messaging-hub-api
          image: registryworkingstork.azurecr.io/playground/messaging-hub-api:1.0.0.0
          # envFrom:
          #   - configMapRef:
          #       name: messaging-hub-api-config
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"