apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../k8s/api
  - configmap.yaml

namePrefix: messaging-hub-api-

labels:
  # Add domain and service labels are used to identify resources specific to this service for selection.
  - pairs:
      domain: messaging-demo
      service: messaging-hub-api
    includeTemplates: true 
    includeSelectors: true 

  # Additional labels not used for selection but useful to be present on all resources for this service.
  - pairs:
      department: IST

# Patch the name of the ConfigMap created by the Azure App Configuration Provider
# and the selectors specific to this service:
patches:
  - target:
      kind: AzureAppConfigurationProvider
    patch: |-
      apiVersion: azconfig.io/v1
      kind: AzureAppConfigurationProvider
      metadata:
        name: messaging-hub-api-appconfig-provider
      spec:
        target:
          configMapName: messaging-hub-api-appconfig
        configuration:
          selectors:
            - keyFilter: "*"
              labelFilter: messaging-hub-api

# Patch the following on the deployment:
#   - Patch the name of the service account to the service's associated workload identity.
#   - Patch name of the image to point to the correct image in the ACR. 
#     The build pipeline will update this with the correct image tag.
#   - Patch the volume named config-volume to point to the above named ConfigMap.
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: messaging-hub-api
      spec:
        template:
          spec:
            serviceAccountName: messaging-hub-api-sa
            containers:
              - name: service-api
                image: registryworkingstork.azurecr.io/playground/messaging-hub-api:0.0.0.0
            volumes:
              - name: config-volume 
                configMap: 
                  name: messaging-hub-api-appconfig

  - target:
      kind: ServiceAccount
    patch: |-
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: messaging-hub-api-sa
        annotations:
          azure.workload.identity/client-id: e75e84b5-b68c-47ef-a88b-419de6ab1af9
