<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  
  <!-- Service Specific Project References -->
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Messaging.Demo.Common\Messaging.Demo.Common.csproj" />
    <ProjectReference Include="..\Messaging.Demo.One.Domain\Messaging.Demo.One.Domain.csproj" />
    <ProjectReference Include="..\Messaging.Demo.One.Infra\Messaging.Demo.One.Infra.csproj" />
  </ItemGroup>

  <!-- Common Project References: Used during local development -->
  <!-- Optional and can be removed but can be included for common project development -->
  <ItemGroup Condition="'$(UseProjectReferences)' == 'true'">
    <ProjectReference Include="..\..\..\..\..\..\common\src\Common.Bootstrapping\Common.Bootstrapping.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\common\src\messaging\Common.Messaging.Entities\Common.Messaging.Entities.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\common\src\messaging\Common.Messaging.Core\Common.Messaging.Core.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\common\src\messaging\Common.Messaging\Common.Messaging.csproj" />
  </ItemGroup>

  <!-- Common NuGet References: Used during service deployment -->
  <ItemGroup Condition="'$(UseProjectReferences)' != 'true'">
    <PackageReference Include="Common.Bootstrapping" Version="1.0.0.22" />
    <PackageReference Include="Common.Messaging.Entities" Version="1.0.0.22" />
    <PackageReference Include="Common.Messaging.Core" Version="1.0.0.22" />
    <PackageReference Include="Common.Messaging" Version="1.0.0.22" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.4" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
  </ItemGroup>
</Project>
