<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  
  <!-- Common Project References: Used during local development -->
  <!-- Optional and can be removed but can be included for common project development -->
  <ItemGroup Condition="'$(UseProjectReferences)' == 'true'">
    <ProjectReference Include="..\..\..\..\..\..\common\src\Common.Bootstrapping\Common.Bootstrapping.csproj" />
  </ItemGroup>

  <!-- Common NuGet References: Used during service deployment -->
  <ItemGroup Condition="'$(UseProjectReferences)' != 'true'">
    <PackageReference Include="Common.Bootstrapping" Version="1.0.0.48" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.4" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.0" />
  </ItemGroup>
  
</Project>
