apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
  - configmap.yaml

labels:
  - pairs:
      solution.io/dept: policy
      solution.io/team: underwriting

patches:
  - target:
      kind: ServiceAccount
      name: solution-service-account
    patch: |-
      - op: replace
        path: /metadata/annotations/azure.workload.identity~1client-id
        value: "${WORKLOAD_CLIENT_ID}"
      - op: replace
        path: /metadata/annotations/azure.workload.identity~1tenant-id
        value: "${WORKLOAD_TENANT_ID}"
