name: 'Setup Environment'
description: 'Setup Node and install dependencies'

inputs:
  first-name:
    description: 'First name of the user'
    required: true
    
  last-name:
    description: 'Last name of the user'
    required: true

outputs:
  full-name:
    description: 'Full name of the user'
    value: ${{ inputs.first-name }} ${{ inputs.last-name }}
  cache-hit:
    description: 'Whether cache was hit'
    value: ${{ steps.fullName.outputs.full-name }}

runs:
  using: 'composite'
  steps:
    - name: Format Name
      id: fullName
      shell: bash
      run: echo "full-name=${{ inputs.first-name }} ${{ inputs.last-name }}" >> $GITHUB_OUTPUT
      
        