<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Messaging.Demo.Two.Api\Messaging.Demo.Two.Api.csproj" />
    <ProjectReference Include="..\Messaging.Demo.Two.Domain\Messaging.Demo.Two.Domain.csproj" />
    <ProjectReference Include="..\Messaging.Demo.Two.Infra\Messaging.Demo.Two.Infra.csproj" />
  </ItemGroup>

</Project>