apiVersion: v1
kind: Service
metadata:
  labels:
    acuitynext.io/dept: policy
    acuitynext.io/team: underwriting
  name: service-one
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: service-one
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    acuitynext.io/dept: policy
    acuitynext.io/team: underwriting
  name: service-one
  namespace: solution
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-one
  template:
    metadata:
      labels:
        app: service-one
    spec:
      containers:
      - image: registryterrapin.azurecr.io/playground/service-one:1.0.0.48
        name: service-one
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
