subscription_id         = "c47473b5-b6e9-476b-853e-a1f5b826e95b"
environment             = "dev"
location                = "eastus"
resource_group_name     = "infrastructure"
cluster_name            = "aks-cluster"
container_registry_name = "registry"
container_registry_sku  = "Basic"
