apiVersion: azconfig.io/v1
kind: AzureAppConfigurationProvider
metadata:
  name:  appconfig-provider
spec:
  endpoint: ${APP_CONFIG_ENDPOINT}
  target:
    configMapName: <patch>
    configMapData: 
      type: json
      key: appsettings.k8s.json
  configuration:
    selectors:
      - keyFilter: <patch>
        labelFilter: <patch>
  auth:
    workloadIdentity:
      serviceAccountName: <patch>
  secret:
    target:
      secretName: <patch>
    refresh:
      enabled: true
      interval: 5m
    auth:
      workloadIdentity:
        serviceAccountName: <patch>