apiVersion: azconfig.io/v1
kind: AzureAppConfigurationProvider
metadata:
  name:  messaging-hub-api-appconfig-provider
spec:
  endpoint: ${APP_CONFIG_ENDPOINT}
  target:
    configMapName: <patch>
    configMapData: 
      type: json
      key: appsettings.k8s.json
  configuration:
    selectors:
      - keyFilter: <patch>
        labelFilter: <patch>
  auth:
    workloadIdentity:
      serviceAccountName: messaging-hub-api-sa