apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      domain: <patch>
      service: <patch>
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: messaging-hub-api-sa
      containers:
        - name: messaging-hub-api
          image: registryworkingstork.azurecr.io/playground/messaging-hub-api:1.0.0.0
          envFrom:
            - configMapRef:
                name: messaging-hub-api-configmap 
          ports:
            - containerPort: 80
          volumeMounts: 
            - name: config-volume
              mountPath: /service/configs
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
      volumes:
        - name: config-volume 
          configMap: 
            name: <patch>