apiVersion: azconfig.io/v1
kind: AzureAppConfigurationProvider
metadata:
  name: service-one-appconfig-provider
spec:
  endpoint: ${APP_CONFIG_ENDPOINT}
  target:
    configMapName: service-one-appconfig
    configMapData: 
      type: json
      key: config.json
  auth:
    workloadIdentity:
      serviceAccountName: solution-sa