apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
  - configmap.yaml
  # - appconfig-provider.yaml

labels:
  - pairs:
      solution.io/dept: policy
      solution.io/team: underwriting
