apiVersion: v1
kind: ServiceAccount
metadata:
  name: solution-sa
  annotations:
    azure.workload.identity/client-id: ${WORKLOAD_CLIENT_ID}
    azure.workload.identity/tenant-id: d105c533-f553-4e8c-b2a5-e5bdf9a67cf1
  labels:
    azure.workload.identity/use: "true"