apiVersion: v1
kind: ServiceAccount
metadata:
  name: solution-sa
  annotations:
    azure.workload.identity/client-id: 00d839fa-8341-4c8d-8c25-91f6bdae6a2c
    azure.workload.identity/tenant-id: d105c533-f553-4e8c-b2a5-e5bdf9a67cf1
  labels:
    azure.workload.identity/use: "true"