apiVersion: v1
kind: ServiceAccount
metadata:
  name: solution-identity
  namespace: solution
  annotations:
    azure.workload.identity/client-id: "b0a73efc-2ee3-4aac-8f50-cc8bf2912558"
    azure.workload.identity/tenant-id: "d105c533-f553-4e8c-b2a5-e5bdf9a67cf1"
  labels:
    azure.workload.identity/use: "true"