apiVersion: azconfig.io/v1
kind: AzureAppConfigurationProvider
metadata:
  name:  demo-one-api-appconfig-provider
spec:
  endpoint: ${APP_CONFIG_ENDPOINT}
  target:
    configMapName: demo-one-api-appconfig
    configMapData: 
      type: json
      key: appsettings.k8s.json
  configuration:
    selectors:
      - keyFilter: "*"
        labelFilter: demo-one-api
  auth:
    workloadIdentity:
      serviceAccountName: demo-one-api-sa