apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-one-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-one-api
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
        app: demo-one-api
    spec:
      serviceAccountName: demo-one-api-sa
      containers:
        - name: demo-one-api
          image: registryworkingstork.azurecr.io/playground/demo-one-api:1.0.0.0
          envFrom:
            - configMapRef:
                name: demo-one-api-configmap
          ports:
            - containerPort: 80
          volumeMounts: 
            - name: config-volume
              mountPath: /service/configs
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
      volumes:
        - name: config-volume 
          configMap: 
            name: demo-one-api-appconfig