apiVersion: v1
kind: ServiceAccount
metadata:
  name: solution-sa
  annotations:
    azure.workload.identity/client-id: ${WORKLOAD_CLIENT_ID}
    azure.workload.identity/tenant-id: ${WORKLOAD_TENANT_ID}
  labels:
    azure.workload.identity/use: "true"