name: Build Shared Microservice Solution

on: 
  workflow_dispatch:
  push:
    branches: 
      - main
    paths:
        - './src/shared/**'  # Trigger only when files in the shared directory are changed
    
jobs:
    build-shared-solution:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Build Shared Solution
          uses: ./.github/actions/dotnet-solution-build
          with:
            solution-path: './src/shared/Playground.Common.sln'