name: CI-Shared Service Solution

on: 
  workflow_dispatch:
  push:
    branches: 
      - main
      - develop
    paths:
        - 'workload/src/common/**'
jobs:
    build:
      uses: ./.github/workflows/dotnet-solution-build.yaml
      with:
        solution-path: './workload/src/common/Playground.Common.sln'
        dotnet-version: '10.0.x'

    package:
      needs: build
      uses: ./.github/workflows/dotnet-solution-package.yaml
      with:
        solution-path: './workload/src/common/Playground.Common.sln'
        dotnet-version: '10.0.x'
      secrets:
        PUBLISH_PACKAGE_TOKEN: ${{ secrets.PUBLISH_PACKAGE_TOKEN }}

