name: Assemble service deployment artifacts
on:
    workflow_call:
        inputs:
            service-root:
                description: 'Name of the service (used for Docker image naming)'
                type: string
                required: true
            retain-days:
                description: 'Number of days to retain the generated artifacts (default: 14)'
                type: number
                required: false
                default: 14

jobs:
    gather-deploy-artifacts:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4                 

            - name: Create artifacts directory
              run: mkdir -p $GITHUB_WORKSPACE/artifacts

            - name: GenerateManifests
              run: |
                for dir in "${{inputs.service-root}}/k8s/envs/*"; do
                    echo "Processing: $dir"
                    (
                        env_name=$(basename "$dir")
                        echo "Running kustomize on Environment: ${env_name} located at: ${dir}"
                        cd $dir
                        
                        kubectl kustomize . > "$GITHUB_WORKSPACE/artifacts/${env_name}-resources.yaml"
                    )
                done

            - name: Archive Kubernetes Manifests
              uses: actions/upload-artifact@v4
              if: success()
              with:
                name: kubernetes-manifests-${{ github.run_id }}
                path: "$GITHUB_WORKSPACE/artifacts/*-resources.yaml"
                retention-days: ${{inputs.retain-days}}
