name: Assemble service deployment artifacts
on:
    workflow_call:
        inputs:
            service-root:
                description: 'Name of the service (used for Docker image naming)'
                type: string
                required: true
            retain-days:
                description: 'Number of days to retain the generated artifacts (default: 14)'
                type: number
                required: false
                default: 14

jobs:
    gather-deploy-artifacts:
        runs-on: ubuntu-latest
        env:
            SERVICE_ROOT: ${{ inputs.service-root }}
            ARTIFACTS_DIR: ${{ github.workspace }}/artifacts
        steps:
            - name: Checkout
              uses: actions/checkout@v4                 

            - name: Create artifacts directory
              run: mkdir -p $ARTIFACTS_DIR

            - name: GenerateManifests
              run: |
                for dir in $SERVICE_ROOT/k8s/envs/*; do
                    echo "Processing: $dir"
                    (
                        ENV_NAME=$(basename $dir)
                        echo "Running kustomize on Environment: ${ENV_NAME} located at: ${dir}"
                        cd $dir
                        
                        kubectl kustomize . > $ARTIFACTS_DIR/$ENV_NAME-resources.yaml
                    )
                done

            - name: List generated artifacts
              run: ls -l $ARTIFACTS_DIR

            - name: Archive Kubernetes Manifests
              uses: actions/upload-artifact@v4
              if: success()
              with:
                name: kubernetes-manifests-${{ github.run_id }}
                path: "${{env.ARTIFACTS_DIR}}/*-resources.yaml"
                retention-days: ${{inputs.retain-days}}
