name: Build, Test, and create Docker Image for .NET Solution
on:
    workflow_call:
        inputs:
            solution-name:
                description: 'Name of the solution the service belongs to (used for Docker image naming)'
                type: string
                required: true
            service-root:
                description: 'Path to the service root directory'
                type: string
                required: true
            service-name:
                description: 'Name of the service (used for Docker image naming)'
                type: string
                required: true
            image-registry:
                description: 'Container registry to push the built image to (e.g., ghcr.io/your-org)'
                type: string
                required: true
            image-tag:
                description: 'Tag to use for the built Docker image (e.g., latest or 1.0.0)'
                type: string
                required: true
            debug:
                description: 'Flag to enable debug logging'
                type: boolean
                default: false
        secrets:
            AZURE_CLIENT_ID:
              description: 'Azure Service Principal Client ID for authentication'
              required: true
            AZURE_TENANT_ID:
              description: 'Azure Tenant ID for authentication'
              required: true
            AZURE_SUBSCRIPTION_ID:
              description: 'Azure Subscription ID for authentication'
              required: true
            READ_PACKAGE_TOKEN:
              description: 'GitHub PAT token with permissions to read packages.'
              required: true
permissions:
  id-token: write
  contents: read
  checks: write

jobs:
    create-service-image:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Azure Login
              uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - name: Azure Container Registry Login
              run: az acr login --name ${{ inputs.image-registry }}

            - name: Set Image Tag
              id: set-image-tag
              run: |
                IMAGE_TAG="${{ inputs.image-registry }}/${{ inputs.solution-name }}/${{ inputs.service-name }}:${{ inputs.image-tag }}"
                echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT
                             
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            
              # Build up to the test-results stage to run tests and export results without building the final image.
            - name: Build and Run Tests, Export Test Results
              uses: docker/build-push-action@v6
              with:
                context: ${{ inputs.service-root }}
                target: test-results
                outputs: type=local,dest=./test-results
                cache-from: type=registry,ref=${{ inputs.image-registry }}/cache/${{ inputs.service-name }}:buildcache
                cache-to: type=registry,ref=${{ inputs.image-registry }}/cache/${{ inputs.service-name }}:buildcache,mode=max

            # Create labels for the final image with build metadata:
            - name: Create Image Label Metadata
              id: metadata
              uses: docker/metadata-action@v5
              with:
                labels: |
                  org.opencontainers.image.title: ${{ github.event.repository.name }}
                  org.opencontainers.image.description: ${{ github.event.repository.description }}
                  org.opencontainers.image.vendor: ${{github.repository.owner.login }}
                  org.opencontainers.image.authors: ${{ github.event.repository.owner.login }}
                  org.opencontainers.image.url: ${{ github.event.repository.html_url }}
                  org.opencontainers.image.source: ${{ github.event.repository.html_url }}
                  org.opencontainers.image.version: ${{ inputs.image-tag }}
                  org.opencontainers.image.created: ${{ github.event.head_commit.timestamp }}
                  

            # Build the final image and scan for vulnerabilities before pushing to the registry:
            - name: Build Final Image
              uses: docker/build-push-action@v6
              with:
                context: ${{ inputs.service-root }}
                push: false
                load: true
                tags: ${{ steps.set-image-tag.outputs.IMAGE_TAG }}
                labels: ${{ steps.metadata.outputs.labels }}
                cache-from: type=registry,ref=${{ inputs.image-registry }}/cache/${{ inputs.service-name }}:buildcache

            - name: List Images in Registry
              if: ${{ inputs.debug }}
              run: docker images -a

            # Scan the final image for vulnerabilities and push only if it passes the scan:
            - name: Scan Image
              uses: aquasecurity/trivy-action@0.28.0
              with:
                image-ref: ${{ steps.set-image-tag.outputs.IMAGE_TAG }}
                severity: HIGH,CRITICAL
                exit-code: '1'

            - name: Push Image
              run: docker push ${{ steps.set-image-tag.outputs.IMAGE_TAG }}
  
            - name: Publish Test Results
              uses: dorny/test-reporter@v1
              if: always()
              with:
                name: Test Results
                path: ./test-results/**/*.trx
                reporter: dotnet-trx