name: Build, Test, and create Docker Image for .NET Solution
on:
    workflow_call:
        inputs:
            solution-name:
                description: 'Name of the solution the service belongs to (used for Docker image naming)'
                type: string
                required: true
            service-root:
                description: 'Path to the service root directory'
                type: string
                required: true
            service-name:
                description: 'Name of the service (used for Docker image naming)'
                type: string
                required: true
            image-registry:
                description: 'Container registry to push the built image to (e.g., ghcr.io/your-org)'
                type: string
                required: true
            image-tag:
                description: 'Tag to use for the built Docker image (e.g., latest or 1.0.0)'
                type: string
                required: true
        secrets:
            AZURE_CLIENT_ID:
              description: 'Azure Service Principal Client ID for authentication'
              required: true
            AZURE_TENANT_ID:
              description: 'Azure Tenant ID for authentication'
              required: true
            AZURE_SUBSCRIPTION_ID:
              description: 'Azure Subscription ID for authentication'
              required: true
permissions:
  id-token: write
  contents: read

jobs:
    create-service-image:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Azure Login
              uses: azure/login@v1
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - name: Login to Azure Container Registry
              run: az acr login --name ${{ inputs.image-registry }}

            - name: Set Image Tag
              id: set-image-tag
              run: |
                IMAGE_TAG="${{ inputs.image-registry }}/${{ inputs.solution-name }}/${{ inputs.service-name }}:${{ inputs.image-tag }}"
                echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT
                
            - name: Build
              uses: docker/build-push-action@v5
              with:
                context: ${{ inputs.service-root }}
                push: false
                tags: ${{ steps.set-image-tag.outputs.IMAGE_TAG }}

  
    
