name: .NET Build and Test Solution
on:
    workflow_call:
        inputs:
            solution-path:
                description: 'Path to the solution file to build'
                type: string
                required: true
            dotnet-version:
                required: false
                type: string
                default: '10.0.x'

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Job Setup
              id: setup
              run: echo "SolutionName=$(basename ${{ inputs.solution-path }})" >> $GITHUB_OUTPUT

            - name: Setup .NET
              uses: actions/setup-dotnet@v5
              with:
                dotnet-version: ${{ inputs.dotnet-version }}
                cache: true

            - name: Restore 
              run: dotnet restore ${{ inputs.solution-path }}

            - name: Build
              run: | 
                dotnet build ${{ inputs.solution-path }} \
                --no-restore \
                --configuration Release

            - name: Test 
              run: |
                dotnet test ${{ inputs.solution-path }} \
                --no-restore \
                --no-build \
                --configuration Release \
                --results-directory ./test-results \
                --logger "trx;LogFileName=test_results.trx"

            - name: Archive Test Results
              uses: actions/upload-artifact@v4
              if: always()  
              with:
                name: test-results-${{ github.run_id }}
                path: ./test-results/*.trx