name: .NET Build and Test Solution
on:
    workflow_call:
        inputs:
            solution-path:
                description: 'Path to the solution file to build'
                type: string
                required: true
            dotnet-version:
                required: false
                type: string
                default: '10.0.x'
            release-version:
                required: false
                type: string
                default: '1.0.0'
            pre-release-version:
                required: false
                type: string
                default: '1.0.0-beta'

permissions:
  contents: read
  packages: write

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Setup .NET
            uses: actions/setup-dotnet@v5
            with:
                dotnet-version: ${{ inputs.dotnet-version }}

          # Restore nuget packages cached by prior workflow:
          - name: Cached NuGet packages
            uses: actions/cache@v4
            with:
              path: ~/.nuget/packages
              key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
              restore-keys: |
                ${{ runner.os }}-nuget-

          # Determine version based on branch:
          - name: Determine Version
            id: version
            run: |
                if [ "${{ github.ref }}" == "refs/heads/main" ]; then
                 VERSION="${{ inputs.release-version }}.${{ github.run_number }}" 
                   echo "package-version=$VERSION" >> $GITHUB_OUTPUT
                   echo "configuration=Debug" >> $GITHUB_OUTPUT
                elif [ "${{ github.ref }}" == "refs/heads/develop" ]; then" 
                   VERSION="${{ inputs.pre-release-version }}.${{ github.run_number }}"
                   echo "package-version=$VERSION" >> $GITHUB_OUTPUT
                   echo "configuration=Debug" >> $GITHUB_OUTPUT
                fi  

          # Creates NuGet packages that can be debugged and publishes to GitHub Packages:
          - name: Create Nuget Packages
            if: ${{ steps.version.outputs.package-version != '' }} 
            run: |
              dotnet pack ${{ inputs.solution-path }} \
              --configuration ${{ steps.version.outputs.configuration }} \
              --output ./packages \
              /p:PackageVersion=${{ steps.version.outputs.package-version }} \
              /p:PublishRepositoryUrl=true \
              /p:IncludeSymbols=true \
              /p:EmbedAllSources=true \
              /p:EmbedUntrackedSources=true \
              /p:DebugType=embedded \
              /p:SymbolPackageFormat=snupkg 

          - name: Publish to GitHub Packages
            if: ${{ steps.version.outputs.package-version != '' }}
            run: |
                dotnet nuget push "./packages/*.nupkg" \
                    --api-key ${{ secrets.GITHUB_TOKEN }} \
                    --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
                    --skip-duplicate
