name: .NET Build and Test Solution
on:
    workflow_call:
        inputs:
            solution-path:
                description: 'Path to the solution file to build'
                type: string
                required: true
            dotnet-version:
                required: false
                type: string
                default: '10.0.x'
            pre-release-version:
                required: false
                type: string
                default: '1.0.0-beta'

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Setup .NET
            uses: actions/setup-dotnet@v5
            with:
                dotnet-version: ${{ inputs.dotnet-version }}

          - name: Cache NuGet packages
            uses: actions/cache@v4
            with:
              path: ~/.nuget/packages
              key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
              restore-keys: |
                ${{ runner.os }}-nuget-

          - name: Determine Version
            id: version
            run: |
               VERSION="${{ inputs.pre-release-version }}.${{ github.run_number }}" 
               echo "package-version=$VERSION" >> $GITHUB_OUTPUT

          - name: Echo
            run: |
                echo "${{ steps.version.outputs.package-version }}"
           