name: Research

on: 
  workflow_dispatch:
  push:
    branches: 
      - main

jobs:
    env_var_examples:
      env:
        TEST_ENV_ONE: "JobLevelEnvVar"
      runs-on: ubuntu-latest
      steps:
        - name: Environment Variables
          run: printenv

        - name: Print Env Var
          env:
            TEST_REPO_VAR: ${{ vars.TEST_VAR }}  # this is a custom environment variable defined at the repository level
          run: |
            echo $GITHUB_ACTOR              # this is a default env var provided by GitHub Actions
            echo $TEST_ENV_ONE              # this is a custom env var defined at the job level
            echo ${{ env.TEST_ENV_ONE }}   # this is a custom env var defined at the job level, but using GitHub Actions expression syntax
            echo $TEST_REPO_VAR              
           
        - name: Set Output Variable
          run: echo "TEST_OUTPUT_VAR_ONE=OutputValue" >> $GITHUB_ENV    # this sets an environment variable that will be available in subsequent steps of the same job 

        - name: Environment Variables
          run: printenv

        - name: Print Env Var
          run: echo $TEST_OUTPUT_VAR_ONE  
          
          
    call_script_example:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Call Script
          run: |
            chmod +x ./test.sh
            SCRIPT_OUTPUT=$(./test.sh)
            echo $SCRIPT_OUTPUT

            # These variables can be used in the current step:
            USER_COUNT=$(echo $SCRIPT_OUTPUT | jq -r '.user_count')
            API_STATUS=$(echo $SCRIPT_OUTPUT | jq -r '.api_status')
            echo "User Count: $USER_COUNT"
            echo "API Status: $API_STATUS"
            printenv
            
            # These variables can also be set as environment variables for subsequent steps:
            echo "USER_COUNT=$USER_COUNT" >> $GITHUB_ENV
            echo "API_STATUS=$API_STATUS" >> $GITHUB_ENV
        - name: Environment Variables
          run: printenv
        - name: Access Prior Set Env Vars
          run: |
            echo "User Count from Env Var: $USER_COUNT"
            echo "API Status from Env Var: $API_STATUS"

    variable_contexts:
      env:
        TEST_ENV_TWO: "JobLevelEnvVar"
      runs-on: ubuntu-latest
      steps:
        - name: gitbub Context
          run: echo '${{ toJSON(github) }}'  # this will print the entire GitHub context, which includes information about the repository, the event that triggered the workflow, and more 

        - name: env Context
          env:
            TEST_ENV_THREE: "StepLevelEnvVar"
          run: echo '${{ toJSON(env) }}'  # this will print all the environment variables available in the current context, including both default and custom variables

        - name: vars Context
          run: echo '${{ toJSON(vars) }}'  # this will print all the
    
        - name: job Context
          run: echo '${{ toJSON(job) }}'  # this will print the job context, which includes information about the current job, such as its name, status, and more