name: Research

on: 
  workflow_dispatch:
  push:
    branches: 
      - main

jobs:
    build:
      env:
        TEST_ENV_ONE: "JobLevelEnvVar"
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Environment Variables
          run: printenv

        - name: Print Env Var
          run: |
            echo $GITHUB_ACTOR              # this is a default env var provided by GitHub Actions
            echo $TEST_ENV_ONE              # this is a custom env var defined at the job level
            echo {{ env.TEST_ENV_ONE }}     # this is a custom env var defined at the job level, but using GitHub Actions expression syntax
           
        - name: Set Output Variable
          run: echo "TEST_OUTPUT_VAR_ONE=OutputValue" >> $GITHUB_OUTPUT 


    
    