name: Research

on: 
  workflow_dispatch:
  push:
    branches: 
      - main

jobs:
    env_var_examples:
      env:
        TEST_ENV_ONE: "JobLevelEnvVar"
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Environment Variables
          run: printenv

        - name: Print Env Var
          run: |
            echo $GITHUB_ACTOR              # this is a default env var provided by GitHub Actions
            echo $TEST_ENV_ONE              # this is a custom env var defined at the job level
            echo {{ env.TEST_ENV_ONE }}     # this is a custom env var defined at the job level, but using GitHub Actions expression syntax
           
        - name: Set Output Variable
          run: echo "TEST_OUTPUT_VAR_ONE=OutputValue" >> $GITHUB_ENV    # this sets an environment variable that will be available in subsequent steps of the same job 

        - name: Environment Variables
          run: printenv

        - name: Print Env Var
          run: echo $TEST_OUTPUT_VAR_ONE  
          
          
    call_script_example:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Call Script
          run: |
            chmod +x ./test.sh
            SCRIPT_OUTPUT=$(./test.sh)
            echo $SCRIPT_OUTPUT
            echo "USER_COUNT=$(echo $SCRIPT_OUTPUT | jq -r '.user_count')" >> $GITHUB_ENV
            echo "API_STATUS=$(echo $SCRIPT_OUTPUT | jq -r '.api_status')" >> $GITHUB_ENV
            echo "User Count: $USER_COUNT"
            echo "API Status: $API_STATUS"
        - name: Environment Variables
          run: printenv


    
    